<?php
/* $Id$ */

/**
* @file
* Very simple DRUPAL module
*/

/**
* Implementation of hook_help().
*/
function campaign_help($section) {
  switch ($section) {
    case 'admin/help#campaign':
      $output = '<p>campaign world help...</p>';
      return $output;
    case 'admin/modules#description':
      return 'Campaigns';
  }
}

/**
* Implementation of hook_menu().
*/
function campaign_menu($may_cache = '') {
  $items = array();

  if ($may_cache) {
  }
  else {

    $items['campaign'] = array(
    'title' => 'Campaigns', // page title
    'description' => "List site contents.",
    'page callback' => 'campaign_list_campaign',
    'access arguments' => array('administer nodes'),
    'file' => 'campaign.admin.inc'
    );

    $items['campaign/new'] = array(
    'title' => 'Campaigns', // page title
    'description' => "View, edit, and delete your site's content.",
    'page callback' => 'campaign_page',
    'access arguments' => array('administer nodes'),
    'file' => 'campaign.pages.inc'
    );


    $items['campaign/save'] = array(
    'title' => 'Campaign', // page title
    'description' => "View, edit, and delete your site's content.",
    'page callback' => 'campaign_save',
    'access arguments' => array('administer nodes'),
    'file' => 'campaign.pages.inc'
    );

  }

  return $items;
}


/**
* Function which generate page (this generate any content - you need only your own code...)
*/
function campaign_block() {
  return '<p>campaign world!</p>';
}

function campaign_all()
{
    echo "here";
}
?>