<?php

$info = array(
  'schemes' => array(
    '#FFFFFF,#0468d1,#006395,#33a3db,#FFFFFF' => t('Default'),
  ),
  'copy' => array(
    'img/gradient.png',
    'logo.png',
  ),
  'gradient' => array(0, 0, 4, 100),
  'fill' => array(
  	'base' => array(),
  	'link' => array(),
  ),
  'slices' => array(
    'img/gradient.png' => array(0, 0, 4, 100),
  ),
  'css' => array(
    'css/colour.css',
  ),
  'preview_image' => 'color/preview.png',
  'preview_css' => 'color/preview.css',
  'base_image' => 'color/base.png',
);